site_name: AOK Documentation
pages:
  - 'index.md'
  - 'node.md'
  - 'desktop.md'
  - 'mobile.md'
  - 'staking.md'
  - 'metadata.md'
  - 'atomic.md'
  - 'rpc.md'
theme:
  name: material
  palette:
    scheme: default
  favicon: assets/images/favicon.png
  logo: assets/logo.png
  generator: false
  custom_dir: overrides
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - admonition
copyright: © 2021 AOK Group Limited. All Rights Reserved.
